version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:1.21.8
    ports:
      - "8081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate

  tax-processor:
    build: .
    ports:
      - "8501:8501"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./credentials:/app/credentials:ro
      - ./data:/app/data:ro
      - ./.env:/app/.env:ro
    depends_on:
      - weaviate
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  weaviate_data:
